version: '3'

services:
    postgres:
        image: postgres:13
        # networks:
        #     - postgres_backend
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
        volumes:
            - data:/data
        restart: always
    # sarum:
    #     build: .
    #     networks:
    #         - postgres_backend
    #     restart: always
    #     ports:
    #         - "5432:5432"
    #         - "8888:8888"
volumes:
    data:

# networks:
#     postgres_backend: